on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Install additional packages
        run: |-
          apt get update && apt get install node npm
          npm install uglify-js -g

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          make

      - name: Push
        run: |-
          gsutil -m rsync -R output gs://${{ secrets.GCS_BUCKET }}
