on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Install node/npm packages
        run: |-
          apt get update && apt get install node npm
          npm install elm-format -g
          npm install uglify-js -g

      - name: Install Elm
        run: |-
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          mv elm /usr/local/bin/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          sed 's/SECRETS_GCS_HOST/${{ secrets.GCS_HOST }}/; s/SECRETS_GCS_API_KEY/${{ secrets.GCS_API_KEY }}/' templates/index.html.template > index.html
          make
